cake_list:
    path: /cakes
    controller: App\Controller\CakeController::list

cake_show:
    path: /cakes/{cakeId}
    controller: App\Controller\CakeController::show
    requirements:
        cakeId: '\d+'

cake_create:
    path: /cakes/create
    controller: App\Controller\CakeController::create

cake_edit:
    path: /cakes/{cakeId}/edit
    controller: App\Controller\CakeController::edit
    requirements:
        cakeId: '\d+'

static_cookie_policy:
    path: /cookie-policy
    controller: App\Controller\StaticPagesController::cookies
