cake_list:
    path: /cakes
    controller: App\Controller\CakeController::list

cake_show:
    path: /cakes/{cakeId}
    controller: App\Controller\CakeController::show
    requirements:
        cakeId: '\d+'

cake_create:
    path: /cakes/create
    controller: App\Controller\CakeController::create

cake_edit:
    path: /cakes/{cakeId}/edit
    controller: App\Controller\CakeController::edit
    requirements:
        cakeId: '\d+'

api_token_create:
    path: /api/token/create
    controller: App\Controller\Api\TokenController::create

api_token_refresh:
    path: /api/token/refresh
    controller: App\Controller\Api\TokenController::refresh

api_cake_list:
    path: /api/cakes
    controller: App\Controller\Api\CakeController::list
