cake_list:
    path: /cakes
    controller: App\Controller\CakeController::list

cake_show:
    path: /cakes/{cakeId}
    controller: App\Controller\CakeController::show
    requirements:
        cakeId: '\d+'

cake_create:
    path: /cakes/create
    controller: App\Controller\CakeController::create

cake_edit:
    path: /cakes/{cakeId}/edit
    controller: App\Controller\CakeController::edit
    requirements:
        cakeId: '\d+'

order_create:
    path: /order/create
    controller: App\Controller\OrderController::create

order_list:
    path: /order/list
    controller: App\Controller\OrderController::list

order_cancel:
    path: /order/{orderId}/cancel
    controller: App\Controller\OrderController::cancel
